# Generated by Django 6.1 on 2026-08-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.IntegerField(default=0, help_text='Lower numbers appear first. e.g. 1 is first, 2 is second.'),
        ),
    ]
